// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEcC6zNbKo4VhCaghloiUvhzgjrEjhHbQ',
    appId: '1:740609124169:web:4757dd2a52c22069d4dc98',
    messagingSenderId: '740609124169',
    projectId: 'dad-project-04',
    authDomain: 'dad-project-04.firebaseapp.com',
    storageBucket: 'dad-project-04.firebasestorage.app',
    measurementId: 'G-C07QKQXH2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA38dV0ZzOnK9g61setdjbschLVfRPiJ7U',
    appId: '1:740609124169:android:a4d7c638e4cfade1d4dc98',
    messagingSenderId: '740609124169',
    projectId: 'dad-project-04',
    storageBucket: 'dad-project-04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv4sR_IXRr-BV_rsw3Z8cw2QF8xdIqUFo',
    appId: '1:740609124169:ios:d2989101b4138068d4dc98',
    messagingSenderId: '740609124169',
    projectId: 'dad-project-04',
    storageBucket: 'dad-project-04.firebasestorage.app',
    iosBundleId: 'com.example.serviceEngineerTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv4sR_IXRr-BV_rsw3Z8cw2QF8xdIqUFo',
    appId: '1:740609124169:ios:d2989101b4138068d4dc98',
    messagingSenderId: '740609124169',
    projectId: 'dad-project-04',
    storageBucket: 'dad-project-04.firebasestorage.app',
    iosBundleId: 'com.example.serviceEngineerTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEcC6zNbKo4VhCaghloiUvhzgjrEjhHbQ',
    appId: '1:740609124169:web:ce4036a1bccb3023d4dc98',
    messagingSenderId: '740609124169',
    projectId: 'dad-project-04',
    authDomain: 'dad-project-04.firebaseapp.com',
    storageBucket: 'dad-project-04.firebasestorage.app',
    measurementId: 'G-ZK66293ZF0',
  );
}
